name: LÖYDÖS
author: Taui
author_website: 'https://tauitaui.com/'
description: >-
  Taui is a Finnish musician interested in things falling apart at the seams,
  as explored in the patterns. The samples in this pack venture into
  off-kilter percussion, unnamed chords and classic supersaws. Enjoy!
patterns:
  - name: LÄPIKUULTAVA
    id: oqjpaewy
  - name: SANKKA
    id: mpjeemzj
  - name: VALAISTU
    id: xzjlnlxj