name: BPB Mini Analogue Collection
author: Bedroom Producers Blog
author_website: 'https://bedroomproducersblog.com/2012/06/13/bpb-mini-analogue-collection-free-sample-pack/'
description: >-
  BPB Mini Analogue Collection contains samples from the following five instruments: Korg Delta, Korg Poly-61m, Korg Poly-800, Solton Project-100 and Lell UDS
  