name: tahti essentials
author: maxjvh
author_website: ''
description: A selection of samples and patterns by the creator of tahti.studio.
patterns:
  - name: infinite drummer
    id: exjxdlpj
  - name: introductions
    id: bxybwlzj
  - name: keep up
    id: arydpbay
  - name: 🏠
    id: xqyrgnrj